name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3'
          - '3.4'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # Caches gems

    - name: Install Google Chrome # Needed for Cuprite/Ferrum
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run tests # Changed name for clarity
      run: bundle exec rake test # Ensure it runs tests, not just default rake task
